# NumPy is a general purpose array processing package.It provides a high performance multidimensional array object and tools for working with these arrays

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
# initially need to import numpy
import numpy as np

In [6]:
m=[1,2,3,4,5] #we created a list
arr=np.array(m) #creates an array based on list

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
arr.shape  #one dimensional array

(5,)

In [11]:
a=[1,2,3,4,5]
b=[1,5,3,6,7]
c=[2,4,6,2,4]
arr=np.array([a,b,c])

In [12]:
arr

array([[1, 2, 3, 4, 5],
       [1, 5, 3, 6, 7],
       [2, 4, 6, 2, 4]])

In [14]:
arr.shape   #output as (rows,columns)

(3, 5)

In [15]:
arr.reshape(5,3) #creates a new array and converts into 5x3 array

array([[1, 2, 3],
       [4, 5, 1],
       [5, 3, 6],
       [7, 2, 4],
       [6, 2, 4]])

In [16]:
arr.reshape(5,4) #not possible as elements are 15 not 20

ValueError: cannot reshape array of size 15 into shape (5,4)

# INDEXING

In [24]:
a=[1,2,3,4,5]
b=[1,5,3,6,7]
c=[2,4,6,2,4]
arr=np.array([a,b,c])

In [25]:
arr[:,:] #will trace all elements

array([[1, 2, 3, 4, 5],
       [1, 5, 3, 6, 7],
       [2, 4, 6, 2, 4]])

In [27]:
arr[1:2,0:3] #will access index 1 row and from 0 to 2nd column

array([[1, 5, 3]])

In [28]:
arr[1:3,:]

array([[1, 5, 3, 6, 7],
       [2, 4, 6, 2, 4]])

In [29]:
arr=np.arange(0,10) #arange is inbuilt function

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr=np.arange(0,10,2) #will create an arry of 0 to 10 skippinfg every 2nd element
arr

array([0, 2, 4, 6, 8])

In [33]:
np.linspace(1,10,50) #inbuilt function

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [34]:
#copy fuction
arr[3:]=100 #will replace element after 3rd index with 100

In [35]:
arr

array([  0,   2,   4, 100, 100])

In [39]:
print(arr)
arr1=arr #creates a copy of array
arr1[2:]=500 #replace element after 2nd index by 500
print(arr1)

[  0   2 500 500 500]
[  0   2 500 500 500]


In [41]:
val=2
arr/2

array([  0.,   1., 250., 250., 250.])

In [42]:
val=2
arr<2

array([ True, False, False, False, False])

In [43]:
np.ones(4) #ctreates an array having elements as 1

array([1., 1., 1., 1.])

In [44]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [45]:
np.ones((2,5),dtype=float) #creates 2x5 matrix having elements as 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
np.random.rand(3,3) #gives random value to 3X3 matrix

array([[0.88698192, 0.19496229, 0.84540404],
       [0.7752601 , 0.61892759, 0.53764602],
       [0.47433866, 0.32469301, 0.03851497]])

In [50]:
a=np.random.randn(2,3)

In [51]:
a

array([[ 1.10703655, -0.86327397,  2.41118918],
       [ 2.14031968,  0.81032093, -0.19206293]])